[package]
name = "preftree"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A prefix tree implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
maplit = "1.0.2"
